BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "CARTPRODUCTS" (
	"CartID"	INTEGER NOT NULL,
	"SKUID"	INTEGER NOT NULL,
	PRIMARY KEY("CartID","SKUID"),
	CONSTRAINT "In Cart" FOREIGN KEY("CartID") REFERENCES "CARTS"("CartID")
);
CREATE TABLE IF NOT EXISTS "CARTS" (
	"CartID"	INTEGER NOT NULL UNIQUE,
	"CustID"	INTEGER NOT NULL,
	"TransID"	INTEGER NOT NULL,
	"CartDone"	INTEGER,
	PRIMARY KEY("CartID" AUTOINCREMENT),
	CONSTRAINT "Customer" FOREIGN KEY("CustID") REFERENCES "CUSTOMERS"("CustID"),
	CONSTRAINT "Related Transaction" FOREIGN KEY("TransID") REFERENCES "",
	CONSTRAINT "EnforceBoolean" CHECK(CartDone < 0 || CartDone > 1)
);
CREATE TABLE IF NOT EXISTS "CUSTOMERS" (
	"CustID"	INTEGER NOT NULL UNIQUE,
	"Email"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL,
	"Username"	TEXT NOT NULL,
	"Name"	TEXT NOT NULL,
	"Surname"	TEXT NOT NULL,
	PRIMARY KEY("CustID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PRODUCTS" (
	"ProdID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Category"	TEXT NOT NULL,
	PRIMARY KEY("ProdID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "SKU" (
	"SKUID"	INTEGER NOT NULL UNIQUE,
	"ProdID"	INTEGER NOT NULL,
	"Colour"	TEXT,
	"Price"	REAL,
	"Description"	TEXT,
	"Picture"	TEXT,
	PRIMARY KEY("SKUID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TRANSACTIONS" (
	"TransID"	INTEGER NOT NULL UNIQUE,
	"CartID"	INTEGER NOT NULL,
	PRIMARY KEY("TransID" AUTOINCREMENT),
	CONSTRAINT "Cart Completed" FOREIGN KEY("CartID") REFERENCES ""
);
COMMIT;
